"use strict";
const fs=require("node:fs"),path=require("node:path"),zlib=require("node:zlib"),crypto=require("node:crypto"),terser=require("terser");
const ROOT=path.join(__dirname,".."),PUBLIC=path.join(ROOT,"public"),OUT=path.join(ROOT,"dist","yandex"),ZIP_PATH=path.join(ROOT,"dist","dread-shift-yandex.zip"),BRIDGE_SOURCE=path.join(ROOT,"yandex","yandex_bridge.js");
function cleanDir(d){fs.rmSync(d,{recursive:true,force:true});fs.mkdirSync(d,{recursive:true});}
function copyDir(a,b){fs.mkdirSync(b,{recursive:true});for(const e of fs.readdirSync(a,{withFileTypes:true})){const x=path.join(a,e.name),y=path.join(b,e.name);e.isDirectory()?copyDir(x,y):fs.copyFileSync(x,y);}}
const read=p=>fs.readFileSync(p,"utf8"),write=(p,s)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s,"utf8");};
function mustReplace(s,a,b,label){if(!s.includes(a))throw new Error("Yandex build target missing: "+label);return s.replace(a,b);}
function getBackend(){const raw=String(process.env.YANDEX_BACKEND_URL||"").trim().replace(/\/+$/,"");if(!raw)throw new Error("Set YANDEX_BACKEND_URL=https://your-backend.example before npm run build:yandex");let u;try{u=new URL(raw);}catch{throw new Error("YANDEX_BACKEND_URL is invalid");}if(u.protocol!=="https:")throw new Error("YANDEX_BACKEND_URL must use https://");if(u.pathname!=="/"||u.search||u.hash)throw new Error("YANDEX_BACKEND_URL must be scheme + host only");return raw;}
function walk(d){let out=[];for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);out=e.isDirectory()?out.concat(walk(p)):out.concat(p);}return out;}
function validateNames(d){for(const f of walk(d)){const rel=path.relative(d,f).split(path.sep).join("/");if(/[\s\u0400-\u04FF]/.test(rel)||!/^[A-Za-z0-9_./-]+$/.test(rel))throw new Error("Yandex archive filename is not allowed: "+rel);}}
function crc32(buf){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function dosDT(d=new Date()){const y=Math.max(1980,d.getFullYear());return {time:(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1),date:((y-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate()};}
function createZip(dir,target){const files=walk(dir).map(full=>({full,name:path.relative(dir,full).split(path.sep).join("/")})),chunks=[],central=[];let offset=0;const dt=dosDT();for(const f of files){const name=Buffer.from(f.name),raw=fs.readFileSync(f.full),def=zlib.deflateRawSync(raw,{level:9}),crc=crc32(raw),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x0800,6);local.writeUInt16LE(8,8);local.writeUInt16LE(dt.time,10);local.writeUInt16LE(dt.date,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(def.length,18);local.writeUInt32LE(raw.length,22);local.writeUInt16LE(name.length,26);chunks.push(local,name,def);const cen=Buffer.alloc(46);cen.writeUInt32LE(0x02014b50,0);cen.writeUInt16LE(0x0314,4);cen.writeUInt16LE(20,6);cen.writeUInt16LE(0x0800,8);cen.writeUInt16LE(8,10);cen.writeUInt16LE(dt.time,12);cen.writeUInt16LE(dt.date,14);cen.writeUInt32LE(crc,16);cen.writeUInt32LE(def.length,20);cen.writeUInt32LE(raw.length,24);cen.writeUInt16LE(name.length,28);cen.writeUInt32LE(offset,42);central.push(cen,name);offset+=local.length+name.length+def.length;}const cStart=offset,cSize=central.reduce((n,b)=>n+b.length,0),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(cSize,12);end.writeUInt32LE(cStart,16);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,Buffer.concat(chunks.concat(central,[end])));return files;}
async function main(){
  const backend=getBackend();cleanDir(OUT);copyDir(PUBLIC,OUT);
  const clientPath=path.join(OUT,"client.js");let client=read(clientPath);
  client=mustReplace(client,'  const proto=location.protocol==="https:"?"wss":"ws";\n  ws=new WebSocket(`${proto}://${location.host}`);','  const proto=location.protocol==="https:"?"wss":"ws";\n  const wsTarget=window.DREAD_WS_URL||(`${proto}://${location.host}`);\n  ws=new WebSocket(wsTarget);',"external WebSocket endpoint");
  client=client.replace('const response=await fetch(`/api/auth/${type}`,','const response=await fetch((window.DREAD_HTTP_BASE||"")+`/api/auth/${type}`, ');
  client=mustReplace(client,'function playSfx(kind,ambient=false){\n  if(!settings.audioEnabled)return;','function playSfx(kind,ambient=false){\n  if(window.__DREAD_PLATFORM_MUTED__||!settings.audioEnabled)return;',"platform audio mute");
  client=mustReplace(client,'  const a=base.cloneNode();','  const a=base.cloneNode();window.__DREAD_ACTIVE_AUDIO__?.add(a);a.addEventListener("ended",()=>window.__DREAD_ACTIVE_AUDIO__?.delete(a),{once:true});',"active audio tracking");
  client=client.replace('metaState=m.meta;if(m.meta?.account)','metaState=m.meta;window.dispatchEvent(new CustomEvent("dread:yandex-meta",{detail:m.meta}));if(m.meta?.account)');
  const frameAnchor="frame();\n})();";if(!client.includes(frameAnchor))throw new Error("Yandex build target missing: final frame anchor");
  const hooks=['window.addEventListener("dread:yandex-pause",()=>{stopGameInput();if(roomMode==="solo"&&state?.started&&!serverPaused){window.__DREAD_YANDEX_AUTO_PAUSED__=true;send("setPaused",{paused:true});}});','window.addEventListener("dread:yandex-resume",()=>{if(window.__DREAD_YANDEX_AUTO_PAUSED__&&roomMode==="solo"&&state?.started&&!pauseOpen){window.__DREAD_YANDEX_AUTO_PAUSED__=false;send("setPaused",{paused:false});}});','window.addEventListener("dread:yandex-rewarded",()=>send("yandexRewarded"));',""] .join("\n");
  client=client.replace(frameAnchor,hooks+frameAnchor);new Function(client);
  const min=await terser.minify(client,{compress:{passes:2},mangle:true,format:{comments:false}});if(!min.code)throw new Error("Terser failed");const h=crypto.createHash("sha256").update(min.code).digest("hex").slice(0,12),bundleRel="assets/game.yandex."+h+".min.js";write(path.join(OUT,bundleRel),min.code);fs.rmSync(clientPath);
  const bridge=read(BRIDGE_SOURCE).replaceAll("__DREAD_BACKEND_URL__",backend);new Function(bridge);write(path.join(OUT,"yandex_bridge.js"),bridge);
  let html=read(path.join(OUT,"index.html"));const clientRe=/<script\s+src=["']\.\/client\.js["']><\/script>/;if(!clientRe.test(html))throw new Error("index client script missing");html=html.replace(clientRe,"");
  const sdk=['<script src="/sdk.js"></script>','<script>window.__DREAD_GAME_SRC__="./'+bundleRel+'";window.DREAD_BACKEND_URL='+JSON.stringify(backend)+';</script>','<script src="./yandex_bridge.js" defer></script>','<style>html.yandex-build #authOverlay{display:none!important}html.yandex-build #logoutBtn,html.yandex-build #profileLogin{display:none!important}#yandexBoot{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;background:#05090b;color:#eaf3ef;font-family:system-ui,sans-serif}.yandex-boot-card{width:min(420px,90vw);display:grid;gap:12px;text-align:center;padding:28px;border:1px solid #213129;border-radius:20px;background:#0b1215;box-shadow:0 25px 80px #0008}.yandex-boot-card b{font-size:25px}.yandex-boot-card span{color:#94a39e;font-size:13px}.yandex-boot-card span.error{color:#ff9a9a}.yandex-boot-card button{padding:12px;border:0;border-radius:10px;background:#dff4e7;color:#07110b;font-weight:900}.hidden{display:none!important}.yandex-reward-btn{position:fixed;right:18px;bottom:74px;z-index:122;display:grid;grid-template-columns:auto auto;grid-template-rows:auto auto;gap:0 6px;align-items:center;padding:9px 12px;border:1px solid #6c5420;border-radius:12px;background:linear-gradient(180deg,#2b2413,#151208);color:#ffe493;box-shadow:0 12px 30px #0008;cursor:pointer}.yandex-reward-btn>b{font-size:13px}.yandex-reward-btn>span{grid-column:2;font-size:8px;color:#ad9b6c}</style>'].join("\n");
  if(!html.includes("</head>"))throw new Error("index head missing");html=html.replace("</head>",sdk+"\n</head>");write(path.join(OUT,"index.html"),html);
  write(path.join(OUT,"style.css"),read(path.join(OUT,"style.css"))+"\nhtml.yandex-build,html.yandex-build body{overscroll-behavior:none;touch-action:manipulation}\n");
  write(path.join(OUT,"yandex-build-info.json"),JSON.stringify({platform:"yandex-games",version:"8.9.9",backendHost:new URL(backend).host,generatedAt:new Date().toISOString(),languages:["ru","en"],target:"desktop"},null,2)+"\n");
  validateNames(OUT);const files=walk(OUT),total=files.reduce((n,f)=>n+fs.statSync(f).size,0);if(total>100*1024*1024)throw new Error("Yandex build exceeds 100 MB");if(!fs.existsSync(path.join(OUT,"index.html")))throw new Error("root index.html missing");const idx=read(path.join(OUT,"index.html"));for(const n of ["/sdk.js","yandex_bridge.js","DREAD_BACKEND_URL"])if(!idx.includes(n))throw new Error("index missing "+n);if(idx.includes("./client.js"))throw new Error("raw client reference survived");
  const zipped=createZip(OUT,ZIP_PATH);console.log("Yandex Games build ready:",ZIP_PATH);console.log("Files:",zipped.length,"Uncompressed MB:",(total/1048576).toFixed(2),"ZIP MB:",(fs.statSync(ZIP_PATH).size/1048576).toFixed(2),"Backend:",backend);
}
main().catch(e=>{console.error("[build:yandex]",e.stack||e);process.exit(1);});
